#!/bin/bash

# Used to reset an environment by
# * Updating the seed table from data.db
# * Removing all tables and content that is migrated from the app
# Prereqs:
# * Azure CLI
# * Export PGxxxx variables for psql to connect to corresponding db (see Settings -> Connect in Azure portal)
#   * Creds can be found in KV
# * kubectl and flux CLI with current context set to env matching the PG variables
# Ex: ./reset-env.sh

set -e

psql << EOF
CREATE TABLE IF NOT EXISTS seed(
    id  integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    data bytea NOT NULL
);
EOF

psql << EOF
\lo_import 'data.db'
SELECT :LASTOID AS lo_oid \gset
INSERT INTO seed (data) VALUES (lo_get(:lo_oid));
SELECT lo_unlink(:lo_oid);
EOF

flux suspend ks -n apps-monitor apps-monitor
kubectl scale deploy -n apps-monitor --replicas=0 apps-monitor
sleep 10 # Wait for app to shutdown

psql -f purge.sql

flux resume ks -n apps-monitor apps-monitor
flux reconcile ks -n apps-monitor apps-monitor
